# Generated by Django 5.1.2 on 2024-11-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmodulepermission',
            options={'ordering': ('-id',), 'verbose_name': 'Grupo Módulo Permiso', 'verbose_name_plural': 'Grupos Módulo Permisos'},
        ),
    ]
