# Generated by Django 5.1.2 on 2024-11-14 01:26

import doctor.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='codigo',
            field=models.CharField(default=doctor.utils.generate_valid_diagnosis_code, max_length=20, unique=True, verbose_name='Código del Diagnóstico'),
        ),
    ]
