# Generated by Django 5.1.2 on 2024-11-17 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_atencion', to='core.doctor', verbose_name='Doctor'),
            preserve_default=False,
        ),
    ]
