# Generated by Django 5.1.2 on 2024-11-18 03:24

import django.db.models.deletion
import doctor.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[doctor.utils.valida_numero_decimal_positivo], verbose_name='Monto')),
                ('metodo_pago', models.CharField(choices=[('EF', 'Efectivo'), ('TR', 'Transferencia Bancaria'), ('PP', 'Pago en línea (Paypal)')], default='EF', max_length=2, verbose_name='Método de Pago')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Pago')),
                ('estado', models.BooleanField(default=True, verbose_name='Pago Confirmado')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='attention.atencion', verbose_name='Atención')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
