# Generated by Django 5.1.2 on 2024-11-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costosatencion',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]
