# Generated by Django 5.1.2 on 2024-11-20 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0002_alter_costosatencion_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarioatencion',
            options={'verbose_name': 'Horario de Atención Doctor', 'verbose_name_plural': 'Horarios de Atención de los Doctores'},
        ),
        migrations.RenameField(
            model_name='horarioatencion',
            old_name='Intervalo_desde',
            new_name='intervalo_desde',
        ),
        migrations.RenameField(
            model_name='horarioatencion',
            old_name='Intervalo_hasta',
            new_name='intervalo_hasta',
        ),
        migrations.CreateModel(
            name='RegistroHorasDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('horas_trabajadas', models.JSONField(verbose_name='Horas Trabajadas')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='attention.horarioatencion', verbose_name='Horario')),
            ],
            options={
                'verbose_name': 'Registro de Horas Trabajadas',
                'verbose_name_plural': 'Registros de Horas Trabajadas',
            },
        ),
    ]
