# Generated by Django 5.1.2 on 2024-11-18 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0002_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total')),
                ('pagado', models.BooleanField(default=False, verbose_name='Pagado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('atencion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='attention.atencion', verbose_name='Atención')),
            ],
        ),
    ]
