# Generated by Django 5.1.2 on 2024-11-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0002_atencion_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='doctor',
        ),
    ]
