# Generated by Django 5.1.2 on 2024-11-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0003_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='servicios_adicionales',
            field=models.ManyToManyField(blank=True, related_name='atenciones', to='attention.serviciosadicionales', verbose_name='Servicios Adicionales'),
        ),
    ]
