# Generated by Django 5.1.2 on 2024-11-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0005_alter_atencion_servicios_adicionales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='servicios_adicionales',
            field=models.ManyToManyField(blank=True, related_name='atenciones', to='attention.serviciosadicionales', verbose_name='Servicios Adicionales'),
        ),
    ]
